Controllers/ListController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using TechJobs.Models;

namespace TechJobs.Controllers
{
    public class ListController : Controller
    {
        internal static Dictionary<string, string> columnChoices = new Dictionary<string, string>();

        // This is a "static constructor" which can be used
        // to initialize static members of a class
        static ListController() 
        {
            
            columnChoices.Add("core competency", "Skill");
            columnChoices.Add("employer", "Employer");
            columnChoices.Add("location", "Location");
            columnChoices.Add("position type", "Position Type");
            columnChoices.Add("all", "All");
        }

        public IActionResult Index()
        {
            ViewBag.columns = columnChoices;
            return View();
        }
                
        public IActionResult Values(string column)
        {
            if (column.Equals("all"))
            {
                List<Dictionary<string, string>> jobs = JobData.FindAll();
                ViewBag.title =  "All Jobs";
                ViewBag.column = column;
                ViewBag.jobs = jobs;
                return View("Jobs");
            }
            else
            {
                List<string> items = JobData.FindAll(column);
                ViewBag.title =  "All " + columnChoices[column] + " Values";
                ViewBag.column = column;
                ViewBag.items = items;
                return View();
            }
        }

        public IActionResult Jobs(string column, string value)
        {
            List<Dictionary<String, String>> jobs = JobData.FindByColumnAndValue(column, value);
            ViewBag.title = "Jobs with " + columnChoices[column] + ": " + value;
            ViewBag.jobs = jobs;

            return View();
        }
      
    }
}









/*
//*******************
// The detail display for a given Job at URLs like /Job?id=17
public IActionResult Index(int id)
{
    int Jobs =

    // DONE - TODO #1 - get the Job with the given ID and pass it into the view
    jobs aJob = new jobs();
    aJob = JobData.FindAll(id);

    return View(aJob);
}
//**************
*/

Views/List/Index.cshtml
<h1>@ViewBag.Title</h1>
<h2>View All</h2>
     @{ 
            //***Sona*** list Index.cshtml---- shows all five options
     }
<ul>
    @foreach (KeyValuePair<string, string> column in ViewBag.columns) {
        <li>
            <a asp-controller="List" asp-action="Values" asp-route-column="@column.Key">@column.Value</a>
        </li>
    }
</ul>

Views/List/Jobs.cshtml
<h1>@ViewBag.title</h1>

<h3>@ViewBag.jobs.Count Result(s)</h3>

@{ 
    // TODO #3 - Use the same list display from Views/Search/Index.cshtml 
    //*****Sona******* 11/25/17
}

@if (ViewBag.jobs != null)
{

    @foreach (var job in ViewBag.Jobs)
    {
        
        <table class="job-listing">

            @foreach (KeyValuePair<string, string> jobfield in job)
            {
                <tr>
                    <td>@jobfield.Key</td>
                    <td>@jobfield.Value</td>
                </tr>
            }

        </table>
    }

}

Views/List/Values.cshtml
<h1>@ViewBag.title</h1>

<table>
@for (int i= 0; i < ViewBag.items.Count; i++)
{
    <tr class="@( i % 2 == 0 ? "even" : "odd" ) ">
        <td><a asp-controller="List" asp-action="Jobs" asp-route-column="@ViewBag.column" asp-route-value="@ViewBag.items[i]">@ViewBag.items[i]</a></td>
    </tr>  
    }   
</table>